---

- hosts: all
  become: true
  tasks:

  - name: updateing repository
    apt:
      update_cache: yes

  - name: install python3
    apt:
      name: python3-pip
      state: latest

  - name: install psutil
    apt:
      name: python3-psutil
      state: latest

  - name: install python3-dev
    apt:
      name: python3-dev
      state: latest

  - name: install matplotlib
    apt:
      name: python3-matplotlib
      state: latest

  - name: install ttkthemes
    apt:
      name: python3-ttkthemes
      state: latest
