---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache2 and php package
    tags: apache,apache2,ubuntu
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: database_server
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


#   when: ansible_distribution in ["Debian", "Ubuntu"]
#   when: ansible_distribution == "Ubuntu" ansible_distribution_version == "24.04"

#  - name: install apache2 and php package on CentOS
#    yum:
#      name:
#        -  httpd
#        -  php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "CentOS"

