- name: install apache2 and php package
  tags: apache,apache2,ubuntu
  apt:
    name:
      -  apache2
      -  libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache2 and php package on CentOS
  tags: apache,centos,httpd
  yum:
    name:
      -  httpd
      -  php
    state: latest
  when: ansible_distribution == "CentOS"

#Para activar un servicio (apache) automaticamente 
- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

#Cambiar email de apache en CentOS
- name: change e-mail address for admin
  tags: apache,centos, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd

#Reiniciar apache si sufre algun cambio en CentOS
- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

#Copiar archivo html en servers
- name: copy default html file for site
  tags: apache,apache2,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
