---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

#   when: ansible_distribution in ["Debian", "Ubuntu"]
#   when: ansible_distribution == "Ubuntu" ansible_distribution_version == "24.04"

#  - name: install apache2 and php package on CentOS
#    yum:
#      name:
#        -  httpd
#        -  php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "CentOS"

